language: objective-c
osx_image: xcode8.3
cache:
  - cocoapods
before_install:
  - gem install slather
  - pod install --repo-update --verbose
env:
  global:
    - WORKSPACE="Gini-iOS-SDK.xcworkspace"
    - SCHEME="Gini-iOS-SDK"
    - SDK=iphonesimulator10.3
    - DESTINATION="OS=10.3,name=iPhone 6S"
    - GH_REF=github.com/gini/gini-sdk-ios.git
    - secure: "mmTWT0WBaAMKNxnPD/Nyxj1sXPZxCMxEaGN4iTg/bxXokrFe4EOnuMGxN2nNWJJmyEKqmZ2VCMJJxqDbmz1xwsI5RgC0Ylywt/nD0oEiKyS0avigyzjG8tqsOY78yl6wJwbsOePKSJq2BniKjpCRN8mfwVoiczwtXjQAKMqAbRA="
    # The write GitHub token for pushing the docs
    secure: "rAfV3cuCa+giZEeTGa+dMutKTqdx03lgcDLN4Dt062l6m4gG+mHKJCWPGrywP44qlvcVAN64947T3y/OxDtzBK91ZrpRyYCRgv0QQGwm5hnSpTh5p7Am5kABfZOhD2kpS3H4Haw48DzUaaCNlcXIs9xj1aWhvnnY0+Ky5j0nt4M="
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c;
after_success:
  - ./scripts/push-documentation.sh
  - slather
  - bash <(curl -s https://codecov.io/bash) -f docs/Coverage/cobertura.xml
